// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b0a5ecf9-6bc8-4ae4-bbc2-f2ff008b408a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_SgpMAVVlM",
    "aws_user_pools_web_client_id": "3315a8a5s3b2jo27j77a60l46j",
    "oauth": {}
};


export default awsmobile;
